# Generated by Django 5.1.4 on 2025-02-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockmatching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=10)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('time_bought', models.DateField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='stockmatching.userprofile')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmatching.stock')),
            ],
        ),
    ]
