# Generated by Django 5.1.4 on 2025-02-08 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stock_logos/')),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('Medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('liquidity', models.CharField(choices=[('high', 'High'), ('Medium', 'Medium'), ('low', 'Low')], default='Medium', max_length=10)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_investments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_liquidity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('risk_factor', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmatching.stock')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmatching.userprofile')),
            ],
        ),
    ]
