# Generated by Django 5.1.4 on 2025-02-09 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stock_logos/')),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('Medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_investments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_liquidity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('risk_factor', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('sectors', models.JSONField(default=list)),
                ('min_market_cap', models.CharField(choices=[('50M', 'Micro-cap ($50M+)'), ('300M', 'Small-cap ($300M+)'), ('2B', 'Mid-cap ($2B+)'), ('10B', 'Large-cap ($10B+)'), ('200B', 'Mega-cap ($200B+)'), ('0', 'No Minimum (All Stocks)')], max_length=20)),
                ('time_frame', models.CharField(choices=[('Long term', 'Long term'), ('Short term', 'Short term')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
